apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ramhacks2019
  labels:
    name: ramhacks2019
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ramhacks2019
  template:
    metadata:
      name: ramhacks2019
      labels:
        name: ramhacks2019
    spec:
      containers:
        - name: ramhacks2019
          image: gcr.io/hotwheels-254409/hot-wheels:v1
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 512Mi
          env:
            - name: DEBUG_MODE
              value: "1"
